### ISSUE TITLE
yarn.lock shouldn't be version managed

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#11]
https://github.com/Natixar/natixar-frontend/blob/ef02efb304be15fcc3db79dec95d395414c956e3/yarn.lock#L1

Ideally you can "git reset --hard" your project before pushing to a new branch, in order to remove the last commits that have included those files and brought nothing related to design. The only changes to make are the inclusion of .env, in which the authentication should be disabled.

**Comment by astowny** [comment]
There is no more yarn.lock file version managed.

**Comment by Math712** [comment]
I check to .gitignore and the yarn.lock is no more version managed.
I close this issue
