### ISSUE TITLE
Time Scale Buttons Bogus Since Request is Always Set to Minutes

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#112]
https://github.com/Natixar/natixar-frontend/blob/ead8cd58e471085638f3ef84d520788ce85e8a27/src/components/network/NetworkIndicator.tsx#L29

## Problem

The row of buttons to select the time scale has no effect on the request. The early devs chose to always request data in minutes and to do aggregation in the front end. This will may break at some point down the chain, although it does not change the volume of information returned by the backend in compressed data point format.

## Steps to Reproduce

1. Authenticate and enter the Dashboard
2. Observe requests logged by the proxy or the development backend after selecting various time scale buttons: it is always "1m" or one minute.

## Desired Behaviour

The desired behaviour is to have the true time step sent to the back end with correct alignment, because data aggregation by the front-end may let users manipulate the data using a combination of dates and scales that violates the

**Comment by lepeuvedic-natixar** [comment]
May be fixed in the current main at 1485f84.
To be checked and eventually closed.

**Comment by ChrisNatixar** [comment]
Front end sends the correctly selected scale to the back-end
