### ISSUE TITLE
Hardcoded reference to "Scope 3"

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#15]
https://github.com/Natixar/natixar-frontend/blob/1b2d3c57f574d5df3aeb3f2e2d580c9bc3107637/src/components/natixarComponents/CategoryCalcTable/index.tsx#L44

"Scopes" is outdated jargon. When taxonomies use the term, it will be supplied by the back-end, but there is no good reason to find this term hardcoded in the front end.

**Comment by lepeuvedic-natixar** [comment]
This use occurs in the "Calculation Method" table, in column 3/3 in the contributors/category.analysis path. 
The Calculation Method is a data quality indicator that refers to data elements, which are not currently provided by the back-end. The back-end stores in the core database the quantified emissions causes, and stores together the calculation method. Various methods can be diversely accurate, and of course, more accurate methods must be used to assess large environmental impacts.

**Comment by ChrisNatixar** [comment]
Temporarily fixed by #106
