### ISSUE TITLE
Hardcoded data

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#16]
https://github.com/Natixar/natixar-frontend/blob/1b2d3c57f574d5df3aeb3f2e2d580c9bc3107637/src/pages/contributor/categoryanalysis.tsx#L16C1-L17C1

The function createData is locally defined and used to define fake hardcoded data.
This is not acceptable for an operational version.
The minimum expected behavior is to disable this irrelevant data and the associated chart, until the whole chain supports it.

**Comment by benjaminpeuple** [comment]
I have disabled the fake data, however I cannot replace it with real ones because I do not know the API route to retrieve this data.

See https://github.com/benjaminpeuple/natixar-front/pull/4

**Comment by lepeuvedic** [comment]
The associated chart is devoid of any fake data, but is still there.

**Comment by lepeuvedic** [comment]
The associated elements must be commented out, since in addition, there is a hardcoded reference to Scope 3.

**Comment by lepeuvedic** [comment]
Reopened to remove the whole table, instead of just having a forever empty table here.
This is temporary: comment code out, don't remove it!

**Comment by astowny** [comment]
@lepeuvedic So for this one can you confirm that we completely remove the table ?

**Comment by ChrisNatixar** [comment]
Temporarily fixed by #106
