### ISSUE TITLE
Added dead code src/components/NavBar.tsx

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#17]
https://github.com/Natixar/natixar-frontend/blob/ef02efb304be15fcc3db79dec95d395414c956e3/src/components/NavBar.tsx#L1

This file is apparently not used.
It is not in the "main" branch.
It includes "./navbar.css" file which does not exist.

Maybe it existed in the source code tree when the original design branch was made, but it is gone in the current version.

**Comment by astowny** [comment]
Fixed in 806f6bcd975ec33ea8c062c065ce8429e4893122

**Comment by lepeuvedic-natixar** [comment]
The referenced commit has no relationship with the issue. Instead, it removes the split of the dashboard over two pages.
