### ISSUE TITLE
Presses on categories taxonomy selector lands us to Error 404 screen

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#19]
https://github.com/Natixar/natixar-frontend/blob/1b2d3c57f574d5df3aeb3f2e2d580c9bc3107637/src/pages/maintenance/404.tsx#L15

Steps to reproduce:
1 - Entre Climate Change Dashboard
2 - Click on BEGES button (top left) to open menu and choose any DIFFERENT option
3 - The main area show a big "Error 404" 
4 - Click on button "Back to Home" to see the effect

The big Error 404 does not show up on the unmodified design.
Note however that the new taxonomy is taken into account.

Expected behavior:
1 - Entre Climate Change Dashboard
2 - Click on BEGES button (top left) to open menu and choose any DIFFERENT option
3 - The top level categories in the Donut chart adapt.

**Comment by astowny** [comment]
Fixed in c45d449c43bc122420646d317eff616a874ea80d
Now, we don't arrive on 404 page but the data is still not displayed, as on main branch.

**Comment by lepeuvedic-natixar** [comment]
OK. It's moving in the right direction, but it still lags behind with respect to the default branch and the bug is not yet fixed.

Of course there is no data because the backend always indexes the data with respect to BEGES categories. Therefore if one selects something else, all the data is filtered out.

But on the main branch, the relevant categories are still updated and it's possible to see the correct categories in the various top categories ("scopes"). It's even possible to select GHG Protocol and to see in scope 3, that the categories are not correctly defined since it only shows "Upstream" and "Downstream". 

In addition, the number of "scopes" changes:
- GHG Protocol should technically have 4 "scopes" with Scope 3 divided in Upstream and Downstream.
- BEGESv5 has six top level categories, which have their own names.

The redesigned branch does not adapt to the changing number of top level categories: it always displays 3 top level categories.
And it always adds "Scope X" to the title, leading to incorrect "Scope 3 Scope 3" title. Interestingly enough, this behaviour occurs even when BEGESv5 is selected and BEGESv5 does not use the term "scope" to describe the six top level categories. I deduce that the categories are not updated.

It would also be really helpful to display the category code (e.g. 1-1) since it would simplify the identification of what is displayed when the display is incomplete (does not show all the top level categories).  And finally, the progress bars showing the amount visually are too long and take up too much space, leading to the truncation of category descriptive text when many times, only words near the end of that text make a difference.
