### ISSUE TITLE
There are up to 6 top level categories in current taxonomies

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#21]
https://github.com/Natixar/natixar-frontend/blob/ef02efb304be15fcc3db79dec95d395414c956e3/src/components/natixarComponents/CO2DonutSection/EmissionByScopeDonutSection.tsx#L45

The BEGESv5 taxonomy has 6 top level categories, but only three colors and three text colors are defined here.
Please use an online palette generator to generate six suitable colors / text colors.

**Comment by astowny** [comment]
Fixed in 938847b9178d8dc442484ba39a5187a4fe3c5cb2

**Comment by lepeuvedic-natixar** [comment]
The change adds more colors to the table, but the fact is that we still do not have the 6 top level categories in BEGESv5.
It may be caused by a problem in getScopesOfProtocol.

**Comment by lepeuvedic-natixar** [comment]
There is a refresh problem: the categories are not refreshed when the categories taxonomy is changed from BEGES to something else. But the refresh can be forced by changing back and forth to the Data page, for example. And even when doing that, there are only four top categories displayed in BEGESv5, when there should be six.
In the original branch, there is a display issue with the big colored rectangles, and only 2 are actually displayed.
