### ISSUE TITLE
Missing Minute and Week

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#22]
https://github.com/Natixar/natixar-frontend/blob/1b2d3c57f574d5df3aeb3f2e2d580c9bc3107637/src/pages/natixar/ClimateChangePage.tsx#L40

In this table which contains an associative map of timescales to various helper functions, the Minute and Week timescales are missing.
This map is the basis on which the buttons are drawn. This issues notice does not imply that fixing the missing time scales here is sufficient to make them work properly.

It is only sufficient to make them appear in the UI.

**Comment by benjaminpeuple** [comment]
Fixed.
See https://github.com/benjaminpeuple/natixar-front/pull/6

Conclusion: 
The following functions were missing:
```
timestampToMinute
sortMinutes
timestampToWeek
sortWeeks
```

Fix:
I had to code each of its functions in **TimeTransformers.ts** and then imported them into the **ClimateChangePage.tsx**

**Comment by astowny** [comment]
Jean-Marc said :"

Apparemment, le problème est d'être capable de générer des étiquettes distinctes pour 10000 périodes consécutives, que ce soient des minutes ou des heures, comme c'est le cas pour les autres.

Pour les minutes, à défaut de pouvoir dynamiquement adapter la description au nombre de périodes, il faut inclure le jour de la semaine (Monday-Sunday) et l'heure pour les représentations à la minute, et il faut inclure la date avec l'année pour les représentations à l'heure (10000 heures font plus d'une année, donc on peut se trouver avec deux mois de janvier dans le jeu de données).

Le tri fait par allKeys.sort(timeSorter) est aussi problématique car il repose sur la capacité à parser les labels de l'axe X correctement pour faire des dates absolues. Ce sont des opérations complexes et longues quand le besoin est de trier des timestamps entiers. Il est évident que si le label est "03:10" il sera classé arbitrairement avant "22:33" alors que je suis peut-être juste en train de consulter les données de la nuit.
"

I would say that a slice is state for each chart in the redux store for that.
