### ISSUE TITLE
Only show Months, Quarters, Years

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#23]
https://github.com/Natixar/natixar-frontend/blob/ef02efb304be15fcc3db79dec95d395414c956e3/src/components/natixarComponents/ChartCard/ChartCard.tsx#L130

The original code uses a loop to flexibly iterate over the defined time scales. 

Problem:
Only three choices appear : Months, Quarters, Years.
Choices Weeks, Days, Hours and Minutes are missing

Expected behaviour:
Show compact button row with all the defined choices. The code should generate UI in a loop.

Cause:
The loop was added later in the main branch.

**Comment by astowny** [comment]
Fixed but it depend on the slots. As I didn't touch it, I have only fixed the loop. It is displaying all except minutes and weeks as on th main branch.

**Comment by lepeuvedic-natixar** [comment]
Fixed
