### ISSUE TITLE
Front-end to back-end API inventory

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#31]
The API supporting the front-end operation exists in at last three related but distinct version. 

- The specification documents, which have a variable quality depending on the endpoint
- The front-end code, in the "as made" configuration
- The surrogate back-end, which sends random data and is very simple to analyze

As a first step, the required task is to write in `/core/co2track-openapi.json` the real API based on an analysis of the actual front-end code, following the OpenAPI 3.0.0 standard. I know that date range picker changes and time scale changes do not currently generate the required back-end data/ranges endpoint requests (because I can observe them decoded). The scope includes the data/ranges endpoint, the mappings endpoint and 

The second step is to write an assessment of the front-end code that would be needed to properly use the /data/ranges endpoint (as a new issue).

**Comment by astowny** [comment]
I added some documentation.

**Comment by astowny** [comment]
I don't understand, did you not make the APIs ?
