### ISSUE TITLE
Dashboard Stacked Area Chart Random Behavior

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#33]
The Apex chart (time series) relies too much on transparency, and it has several negative consequences which must be corrected:

1 - Because the three curves are strictly stacked and only take positive values, the two curves in the bottom are always show superimposed with the other two colors. Due to transparency, the colors do not match exactly with the legend, where colors are also transparent, but shown on a white background.
![Colors do not match legend](https://github.com/Natixar/natixar-frontend/assets/157426470/6db96956-6e2a-4f4a-8a7f-d458a3a42205)

2 - The order in which the three curves operations / downstream / upstream appear is randomly changing every time the data is refreshed. 

Bug is also present on main branch.

**Comment by ChrisNatixar** [comment]
Appears to be fixed
