### ISSUE TITLE
Interaction with Total Emissions chart legend is illogical

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#4]
The Total Emissions chart on the dashboard is a stacked curves type chart. It is typically showing scope 1, scope 2 and scope 3 on top of each other, even though somehow the devs decided that they would show upstream, downstream and operations instead (which is a more stable set of concepts than scopes, but nevertheless not the requirement).

The issue is generic and linked to how these charts behave, but it is particularly problematic with this chart. I tend to believe that the chart library does not know stacked curves, and that the devs have themselves added the numbers to make the three curves, then they have literally displayed curve1 on top of curve1+curve2, which itself is shown on top of curve1+curve2+curve3. 

The library has a built-in function which focuses visually on one curve when the pointer is on the corresponding legend field, letting the color of the others go transparent. When showing curve1, it is fine but there is little added value because the variations of curve1 are permanently displayed. When showing curve2, it actually shows curve1+curve2, as if it were curve2. This is an error.  The same occurs for curve3, which is displayed as curve1+curve2+curve3.

Solutions: disable the feature / find a better library that understands stacked curves natively / find a better library like bokeh, that understands area charts having min and max values ?

**Comment by astowny** [comment]
The feature has been diasbled as we don't see the legend now.

**Comment by Math712** [comment]
To me the probleme is fix, so i close the issue
