### ISSUE TITLE
Filters Must Indicate "All" When Nothing is Selected

### ISSUE THREAD

**Issue by lepeuvedic** [Natixar/natixar-frontend#56]
## Problem
The business entity, geographics area and scope filters are deactivated when nothing is selected. This is intentional, because it does not make sense to select no data, and therefore it does not make sense to allow completely empty filters. It was a design decision to assimilate a complete deselection of filter items to a complete selection of filter items. The specification said:

**The Slicer is integrated in a banner and is always visible when scrolling down. When more than one entity is selected, the Slicer shall show either the values "All” or “Several”. No selection is equivalent to “All” and to selecting all the entities, or the top entities.**

The filter gadgets are empty when nothing is selected, and show partial and misleading, unusable, information in multi-selection cases.
![Filters Multiselect](https://github.com/Natixar/natixar-frontend/assets/26287656/6e6967e8-6ad7-40a6-a446-d691a809d95c)

In partial selection cases, opening the filter gives strictly no information on the current selection, due to the fact that partially selected categories are not differentiated from unselected categories. Once we correct the first problem and display "Several", the user will have not even a hint regarding what is actually selected and how to find it.
![No Half-checked Confusion](https://github.com/Natixar/natixar-frontend/assets/26287656/89ab93ca-6d02-48d7-9a67-96caaae0c2d7)

## Steps to Reproduce:

1. Authenticate and enter the Dashboard
2. Open the Entity filter, select "GrDF" and open the subsections and select "Direction Industrielle"
3. Observe partial and truncated information in the Entity filter and emptiness in Geographic and Scope filters

## Desired Behavior

1. The (translatable) term "All" is written in a distinct font (e.g. italics) or color (not flashy) whenever the software acts as if all items were selected (no filtering). This occurs either when all the visible boxes are checked or when no box is checked at all.
2. The (translatable) term "Several" is written the same distinct font or color when more than one item is selected but some items are not selected, unless the filter has enough space to display the active choices in their entirety.
3. The check boxes in the hierarchy must have a "half-checked" state when only some of their children are selected. This is commonly depicted either as a "square in a square" symbol or a "dash in a square" symbol.

**Comment by lepeuvedic-natixar** [comment]
Partial correction: only point 1 is fixed and the Scope filter has been omitted, which improves the appearance when entering the Dashboard.
