### ISSUE TITLE
On NatixarExpandableBar, the Per-scope Totals do not Appear Except on BEGES

### ISSUE THREAD

**Issue by lepeuvedic** [Natixar/natixar-frontend#59]
## Problem
When the taxonomy chosen is anything else than BEGES, the totals shown on the <NatixarExpandableBar> are not shown.
![No Scope Totals GHG Protocol](https://github.com/Natixar/natixar-frontend/assets/26287656/a14acd7d-9e6f-4645-85cd-fa345a6ff71d)

## Steps to Reproduce

1. Authenticate and enter the Dashboard
2. Select GHG Protocol with the "BEGES" button (taxonomy selector)
3. Observe in Scope1 that there is no total shown anymore, where the total was when the selected taxonomy was BEGES.
4. Select BEGES again
5. Observe in Scope1 NatixarExpandableBar that the total is now equal to the donut total at 179.9ktCOeq

## Desired Behavior
The totals in the <NatixarExpandableBar> widgets are correctly displayed and computed, even when they are zéro, even when the selected taxonomy is not BEGES.

**Comment by astowny** [comment]
Fixed by @lnrreact , and already is on dev branch
