### ISSUE TITLE
Main Dashboard Scopes filter widget poor design

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#6]
The design of the filter widget is particularly poor. It is a multselection widget like its neighbors, but there is no clear indication of what is selected. It tries to display all the selected choices in the widget itself, but the widget is too small to display even one choice entirely. Without being able to see what is currently selected, even when the menu is opened, users are in trouble to make proper settings. In addition, when charts are printed, the filter settings determining what is displayed, are unclear.

**Comment by astowny** [comment]
We can add ellipsis (...) if the selected text is overflowing.
