### ISSUE TITLE
Authentication interferes with some pages

### ISSUE THREAD

**Issue by lepeuvedic-natixar** [Natixar/natixar-frontend#7]
At last two pages, directly accessible via links <Link2> from the navigation
contributors/scope/:id   ->  contributors/category-analysis/:id
contributors/top/scope/:id -> contributors/analysis/:id
fail in the router and the browser window becomes all white with written "Not Found".
Probably more pages fail in the same way, but they cannot be reached anyways.

Correction: navigation to all pages shall work when authentication is enabled like when it is disabled.

Note that on development instances with live reload, the application reloads and the user gets back to the dashboard.

**Comment by benjaminpeuple** [comment]
Issue fixed.
See https://github.com/benjaminpeuple/natixar-front/pull/1

Conclusion:
The problem was due to a loading time that was too fast, isAuthenticated was not asynchronous.

Fix:
To fix this, I had to add a delay of 500 ms before rendering the different routes.

**Comment by lepeuvedic** [comment]
Erreur "vite build" sur Render.com:

```
src/app-layout/index.tsx(48,6): error TS2786: 'AuthGuard' cannot be used as a JSX component.
Its return type 'void | ReactElement<any, string | JSXElementConstructor<any>> | null' is not a valid JSX element.
May 3 06:48:29 PM    Type 'void' is not assignable to type 'Element | null'.
```

Très probablement liée à l'utilisation de navigate() dans l'opérateur ternaire et dans le corps du composant.

**Comment by astowny** [comment]
Untestable on my side as the issue occurs once auth is enabled : https://co2track-pr-07-onrender.natixar.pro/ or https://co2track-pr-7-onrender.natixar.pro/ have "Not found"

**Comment by astowny** [comment]
As well as on https://natixar-pr-7.onrender.com/

**Comment by lepeuvedic-natixar** [comment]
The oldest still active preview is #42. They are purged after a while. The other active previews are 63 67 68 70 and 73. One cannot access #7 anymore.
